#!/bin/sh

hide_cursor() {
    if command -v tput > /dev/null; then
        tput civis
    fi
}

show_cursor() {
    if command -v tput > /dev/null; then
        tput cnorm
    fi
}

get_columns() {
    if command -v tput > /dev/null; then
        tput cols
    elif command -v stty > /dev/null; then
        stty size | cut -d' ' -f2
    else
        echo "${COLUMNS:-80}"
    fi
}

trap show_cursor EXIT
hide_cursor

columns=$(get_columns)
while IFS='' read -r update; do
    progress="${update% *}"
    size="${update#* }"
    width="$(((progress * columns) / size))"
    printf '\r'
    printf '█%.0s' $(seq 1 "$width")
done
