#!/bin/sh

hide_cursor() {
    if command -v tput > /dev/null; then
        tput civis
    fi
}

show_cursor() {
    if command -v tput > /dev/null; then
        tput cnorm
    fi
}

get_columns() {
    if command -v tput > /dev/null; then
        tput cols
    elif command -v stty > /dev/null; then
        stty size | cut -d' ' -f2
    else
        echo "${COLUMNS:-80}"
    fi
}

is_number() {
    case "$1" in
        ''|*[!0-9]*) false;;
        *) true;;
    esac
}

draw_bar() {
    printf '\r'
    printf "$1%.0s" $(seq 1 "$2")
}

trap show_cursor EXIT
hide_cursor

columns=$(get_columns)
while IFS= read -r line; do
    progress="${line% *}"
    size="${line#* }"
    if is_number "$progress" && is_number "$size"; then
        draw_bar '█' "$(((progress * columns) / size))"
    else
        printf -- "\n%s\n" "$line" >&2
        exit 1
    fi
done
