#!/bin/sh

hide_cursor() {
    if command -v tput > /dev/null; then
        tput civis
    fi
}

show_cursor() {
    if command -v tput > /dev/null; then
        tput cnorm
    fi
}

get_columns() {
    if command -v tput > /dev/null; then
        tput cols < /dev/tty 2> /dev/tty
    elif command -v stty > /dev/null; then
        stty size < /dev/tty 2> /dev/tty | cut -d' ' -f2
    else
        echo "${COLUMNS:-80}"
    fi
}

is_number() {
    case "$1" in
        ''|*[!0-9]*) false;;
        *) true;;
    esac
}

trap show_cursor EXIT
hide_cursor

bar_width=0
columns="$(get_columns)"
while IFS= read -r line; do
    progress="${line% *}"
    size="${line#* }"
    if is_number "$progress" && is_number "$size"; then
        new_width="$(((progress * columns) / size))"
        while [ "$new_width" -gt "$bar_width" ]; do
            printf '█'
            bar_width="$((bar_width + 1))"
        done
    else
        printf -- "\n%s\n" "$line" >&2
        exit 1
    fi
done
printf '\n'
